version: "2"

services:
  filestore:
    image: tebro/filestore
    ports:
      - "10000:10000"
    networks:
      - notebook
    environment:
      STORAGE_FILE_PATH: "/filestore"
      STORAGE_BACKEND: "file"
    volumes:
      - "filestore:/filestore"

  mongo:
    image: mongo
    networks:
      - notebook

  web:
    build: .
    networks:
      - notebook
    ports:
      - "80:80"
    environment:
      MONGODB_SERVER: "mongo"
      MONGODB_NAME: "notebook"
      FILESTORE_SERVER: "filestore"
      FILESTORE_PORT: 10000

networks:
  notebook:
volumes:
  filestore:
